# name of the workflow
name: 01 - building 1st workflow
#on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: print hello 
        run: echo "Hello"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: success step 
        run: |
          echo "I will success"
          exit 0
      - name: say goodbye
        run: echo "Goodbye"          