name: 02-github action workflow events
on: 
#    push: 
#    pull_request: 
#    schedule:
#        - cron: '0 */12 * * *'
    workflow_dispatch:


jobs:
    echo:
        runs-on: ubuntu-latest
        steps: 
            - name: show the event
              run: echo "I have been triggred by an ${{ github.event_name }}  event."
