name: 03-workflow_runners
on: push
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: show-os
              run: |
                echo "Runner OS: $RUNNER_OS"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: show windows os
              shell: bash         # Windows has the bash installed in it.. or else below commads wont work on Windows machine.
              run: |
                echo "Job is running on the Windows Runner"
                echo "Runner OS: $RUNNER_OS" 
    mac-echo:
        runs-on: macos-latest
        steps:
            - name: show Mac-OS
              run: |
                echo "Runner OS name: $RUNNER_OS"