#1. Checkout the code from the repository
#2. Install deps of our react application
#3. Execute automated tests
name: 04-workflow_actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: printfiles
              run: ls
            - name: Node setup
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Installaing Dependencies
              run: npm ci
              working-directory: 04-workflow_actions/react-app
              #run: |
              #  cd 04-workflow_actions/react-app
              #  npm ci





