name: 11 - Working with Inputs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean  # boolean ; choice ; envirment <--- 3 options
        description: "Skip deployment and only print build output"
        default: false
      target:
        type: environment
        description: "Environment to deploy to (dev/stage/prod)"
        required: true
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: Relase from which to build and deploy  

jobs:
  build:
    runs-on: ubuntu-latest        
    steps:
      - name: Build
        run: |
          echo "Building from tag: ${{ inputs.tag }}"
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run }}
    environment: ${{ inputs.target }}
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ inputs.target }}"   