name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - ${{}}
on:
  workflow_dispatch:
    inputs:
      target-env:
        choice: [production, staging]
env:
  working-directory: 17-custom-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: action/checout@v4
      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 20.x                         #### defined in action.yaml file in composite
          working-dir: ${{ env.working-directory }}   #### defined in action.yaml file in composite
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build 